//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCLink.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HospInfo
    {
        public string Rowid { get; set; }
        public Nullable<int> HospOrder { get; set; }
        public string HospBranchOffice { get; set; }
        public string HospID { get; set; }
        public string HospName { get; set; }
        public string HospAddress { get; set; }
        public string HospAreaCode { get; set; }
        public string HospPhone { get; set; }
        public string HospClass { get; set; }
        public string HospType { get; set; }
        public string HospKind { get; set; }
        public string HospTermDate { get; set; }
        public string HospDean { get; set; }
        public string HospHis { get; set; }
        public Nullable<bool> HospLis { get; set; }
        public string HospLoginPassword { get; set; }
        public string HospRank { get; set; }
        public string HospGroup { get; set; }
        public string HospMedicalGroup { get; set; }
    }
}
